name: fiadisyon
description: Fiskindal adisyon
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  common:
    path: packages/common
  connectivity_plus: ^4.0.1
  core:
    path: packages/core

  easy_logger: ^0.0.2
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  intl: ^0.18.0
  flutter_bloc: ^8.1.3
  formz: ^0.6.1
  gen:
    path: packages/gen
  get_it: ^7.6.6
  google_fonts: ^6.1.0
  kartal: ^3.5.0
  logger: ^2.0.2+1
  syncfusion_flutter_pdfviewer: ^24.2.5
  theme:
    path: packages/theme
  vexana: ^3.5.4
  widgets:
    path: packages/widgets

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  device_preview: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.4.0
  mockito: ^5.4.4
  mocktail: ^1.0.0
  patrol: ^3.4.0
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
     - assets/translations/
     - assets/docs/