name: gen
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"


dependencies:
  flutter:
    sdk: flutter

  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  lottie: ^2.6.0

  json_annotation: ^4.8.1
  # for network model
  vexana: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2



   
flutter_gen:
  output: lib/src/asset/
  line_length: 80
  

flutter: 
  assets:
    - assets/env/
  #   #- assets/icons/
  #   #- assets/images/
   
